### ISSUE TITLE
Metric tracking is clunky

### ISSUE THREAD

**Issue by learning-luke** [BayesWatch/pytorch-experiments-template#2]
Perhaps use a dictionary with functions as keys?

**Comment by AntreasAntoniou** [comment]
I did some initial work on this some time ago, but I never posted it here. So, the two commits that summarize my changes are:
- [8b3152ac](https://github.com/BayesWatch/pytorch-experiments-template/commit/8b3152ac1e596343230cf29380653ed3eb0e6942)
- [9a342c39](https://github.com/BayesWatch/pytorch-experiments-template/commit/9a342c3920997ad2d53ff91b9fe54ff747bf79aa)

**Comment by jack-willturner** [comment]
What's the current status of this? If it's done we should merge it into main

**Comment by AntreasAntoniou** [comment]
This is done I believe.
