### ISSUE TITLE
Some better abstraction with parts of the code in the main train file

### ISSUE THREAD

**Issue by learning-luke** [BayesWatch/pytorch-experiments-template#3]

**Comment by jack-willturner** [comment]
On this note: I know it creates some duplication but I much prefer having a `train` and `test` function separate (rather than just `run_epoch` with a flag).

**Comment by AntreasAntoniou** [comment]
Yes. Train and test should be separated, as in many cases you want to do one and not the other, and even more often, you want to do one differently than the other.

**Comment by AntreasAntoniou** [comment]
Started working on this, let me know of any comments.

**Comment by jack-willturner** [comment]
A couple of personal preferences: 
1. `args` should be within the train file. 
2. data location should be extracted from an environment variable (e.g. I keep my data_loc in `PYTORCH_DATA_LOC`. that way I don't need to pass a different data loc per machine - on `wolfburn` it's set to `/disk/scratch_ssd/`, on my laptop it's set to `~/datasets`)
3. currently no data parallel or device management? 
4. order should go: general imports -> argparse -> os.environ['CUDA_VISIBLE_DEVICES'] = args.GPU ->  import torch or anything torch related. I don't know if this is still an issue in pytorch?

**Comment by learning-luke** [comment]
I agree with 1 and 3. I don't agree with 2 because it's a bit against our original design protocol of minimal additional setup. I get around this easily by having my data loc one folder back in the hierarchy wherever I am working. 

As for 3, that's really easy to fix. And we should add distributed training for sure. But, as a flag. It shouldn't be default I think. 

As for 4, I think we all do this process differently. I set which device(s) are available for each run I do. Again, this is additional overhead but also plays well with any system and GPU availability. If there are 8, for instance, but I only want 2, I can limit this easily. Ideally, I think we should find a easy to probe which GPUs are available, have a flag of max GPUs to use, and automate distribution according to these. This will work super well for our group.

**Comment by jack-willturner** [comment]
> I get around this easily by having my data loc one folder back in the hierarchy wherever I am working.

Doesn't this require you to have your work saved on the SSDs? I.e. `scratch_ssd` instead of `scratch`? 

My understanding was that the SSDs were mainly intended for holding the datasets, whereas the HDDs are for saving model checkpoints and work?

> I think we should find a easy to probe which GPUs are available, have a flag of max GPUs to use, and automate distribution according to these.

Oooh I like this idea.

**Comment by AntreasAntoniou** [comment]
The automation of GPU allocation is something I've already implemented in
the past. I can share that code with you later.
