### ISSUE TITLE
Experiment folder not named according to any hyper parameters, but as an argument. Issue?

### ISSUE THREAD

**Issue by learning-luke** [BayesWatch/pytorch-experiments-template#8]

**Comment by AntreasAntoniou** [comment]
Definitely an issue if you are doing a complex hyperparameter sweep. On the other hand the variables to be added to the name need to be kept to a minimum, otherwise risking the name becoming too long and useless.

**Comment by learning-luke** [comment]
That's why it is like it is.

**Comment by AntreasAntoniou** [comment]
This has also been addressed.
